In [2]:
import sys;
if sys.path[-1] != sys.path[0][:-16]:
    sys.path.append(sys.path[0][:-16]);

import md_scaling;
import numpy as np;
import pandas as pd;
import lab2.main_comp as mp;
from common.functions import eig_matlab

[[ 9.99840586e-01 -1.12179951e-08  1.78550637e-02]
 [-8.73083939e-01 -6.88738302e-09 -4.87569929e-01]
 [-8.54871108e-01 -6.08623126e-09  5.18840428e-01]]


data loading

In [3]:
data = pd.read_csv('input_data.csv', sep = ',', header = None).to_numpy();
print(data)

[[1.4650e+04 1.2230e+03 1.0800e+01 1.4840e+02 2.6400e-01]
 [4.3643e+03 6.0600e+02 2.0000e-01 7.6500e+01 2.3400e-01]
 [1.4000e+03 3.0600e+02 8.2000e+00 1.5730e+02 2.7400e-01]]


data normalisation

In [4]:
norm_data = md_scaling.normalize_data(data)
print(norm_data)
pd.DataFrame(norm_data).to_excel('temp.xlsx')

[[2.15290262 1.71850117 1.6875     1.16483516 1.02590674]
 [0.64135924 0.85152225 0.03125    0.60047096 0.90932642]
 [0.20573813 0.42997658 1.28125    1.23469388 1.06476684]]


compution of objects distances

In [5]:
distances = md_scaling.object_distances(norm_data)
print(distances)
pd.DataFrame(norm_data).to_excel('temp.xlsx')

[[0.         2.47218078 2.37132338]
 [2.47218078 0.         1.53504623]
 [2.37132338 1.53504623 0.        ]]


In [6]:
mat = np.array([[0, 2.47, 2.38],[2.47, 0, 1.54],[2.38, 1.54, 0]]);
b = md_scaling.b_matrix(mat);
pd.DataFrame(b).to_excel('temp.xlsx')

In [10]:
res = mp.principal_comp_full_compution(b);
print('корреляционная матрица')
print(res['R'])
print('собсвенные числа корреляционной матрицы')
print(res['L'])
pd.DataFrame(res['L']).to_excel('temp.xlsx')
print('собсвенные векторы корреляционной матрицы')
print(res['V'])
pd.DataFrame(res['V']).to_excel('temp.xlsx')
print('квадраты собственных чисел')
print(res['L_sqrt'])
pd.DataFrame(res['L_sqrt']).to_excel('temp.xlsx')
print('матрица факторных нагрузок')
print(res['A'])
pd.DataFrame(res['A']).to_excel('temp.xlsx')
print('матрица новых координат')
print(res['F'])

корреляционная матрица
[[ 1.         -0.88165035 -0.8454709 ]
 [-0.88165035  1.          0.49340324]
 [-0.8454709   0.49340324  1.        ]]
собсвенные числа корреляционной матрицы
[[ 2.49276137e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.10321669e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  5.07238628e-01]]
собсвенные векторы корреляционной матрицы
[[ 0.63327218 -0.77352301  0.02507005]
 [-0.55298792 -0.474911   -0.68459032]
 [-0.5414524  -0.41966857  0.7284968 ]]
квадраты собственных чисел
[[1.57884812e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.45024711e-08 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.12206872e-01]]
матрица факторных нагрузок
[[ 9.99840586e-01 -1.12179951e-08  1.78550637e-02]
 [-8.73083939e-01 -6.88738302e-09 -4.87569929e-01]
 [-8.54871108e-01 -6.08623126e-09  5.18840428e-01]]
матрица новых координат
[[ 1.41398801e+00 -1.15115765e-08 -2.52567495e-02]
 [-7.28866992e-01 -1.13096219e-09 -1.21192116e+00]
 [-6.85121019e-01  1.07360

In [14]:
print(res['L'][0,0]*res['V'][:,0])
print(np.dot(res['R'],res['V'][:,0]))

[ 1.57859642 -1.37846693 -1.34971164]
[ 1.57859642 -1.37846693 -1.34971164]


In [17]:
from common.functions import eig_matlab

[L, V] = eig_matlab(b)
L = np.sqrt(L);

print(np.dot(V,L))

[[ 1.53256051e+00 -1.14569081e-08 -4.75212556e-02]
 [-8.37523387e-01 -1.14569081e-08 -7.42936455e-01]
 [-6.95037127e-01 -1.14569081e-08  7.90457710e-01]]
